In [4]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    confusion_matrix,
    classification_report,
    roc_auc_score
)

from imblearn.over_sampling import SMOTE

from sklearn.ensemble import IsolationForest

import warnings
warnings.filterwarnings('ignore')

In [3]:
from google.colab import files

uploaded = files.upload()

Saving creditcard.csv to creditcard.csv


In [6]:

# DATA CLEANING & PREPROCESSING


import pandas as pd

# Load dataset

df = pd.read_csv("creditcard.csv")

# Display first rows

print(df.head())

# Dataset shape

print("\nDataset Shape:")
print(df.shape)

# Check missing values

print("\nMissing Values:")
print(df.isnull().sum())

# Remove duplicate rows

df = df.drop_duplicates()

# Dataset shape after duplicates removed

print("\nShape After Removing Duplicates:")
print(df.shape)

# Check class distribution

print("\nClass Distribution:")
print(df['Class'].value_counts())

# Dataset info

print("\nDataset Info:")
print(df.info())

   Time        V1        V2        V3        V4        V5        V6        V7  \
0   0.0 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388  0.239599   
1   0.0  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361 -0.078803   
2   1.0 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499  0.791461   
3   1.0 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203  0.237609   
4   2.0 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921  0.592941   

         V8        V9  ...       V21       V22       V23       V24       V25  \
0  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928  0.128539   
1  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846  0.167170   
2  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281 -0.327642   
3  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575  0.647376   
4 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267 -0.206010   

        V26       V27       V28 

In [7]:
#feature scaling
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

df['Amount'] = scaler.fit_transform(
    df[['Amount']]
)

df['Time'] = scaler.fit_transform(
    df[['Time']]
)

print(df.head())

       Time        V1        V2        V3        V4        V5        V6  \
0 -1.996823 -1.359807 -0.072781  2.536347  1.378155 -0.338321  0.462388   
1 -1.996823  1.191857  0.266151  0.166480  0.448154  0.060018 -0.082361   
2 -1.996802 -1.358354 -1.340163  1.773209  0.379780 -0.503198  1.800499   
3 -1.996802 -0.966272 -0.185226  1.792993 -0.863291 -0.010309  1.247203   
4 -1.996781 -1.158233  0.877737  1.548718  0.403034 -0.407193  0.095921   

         V7        V8        V9  ...       V21       V22       V23       V24  \
0  0.239599  0.098698  0.363787  ... -0.018307  0.277838 -0.110474  0.066928   
1 -0.078803  0.085102 -0.255425  ... -0.225775 -0.638672  0.101288 -0.339846   
2  0.791461  0.247676 -1.514654  ...  0.247998  0.771679  0.909412 -0.689281   
3  0.237609  0.377436 -1.387024  ... -0.108300  0.005274 -0.190321 -1.175575   
4  0.592941 -0.270533  0.817739  ... -0.009431  0.798278 -0.137458  0.141267   

        V25       V26       V27       V28    Amount  Class  
0  0.12

In [8]:
# define features and target
X = df.drop('Class', axis=1)

y = df['Class']
print(X.shape)

print(y.shape)

(283726, 30)
(283726,)


In [9]:
# train- test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

In [10]:
#Handle Imbalanced Data using SMOTE
from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)

X_train_smote, y_train_smote = smote.fit_resample(
    X_train,
    y_train
)

print(y_train_smote.value_counts())

Class
0    226597
1    226597
Name: count, dtype: int64


In [ ]:
from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

In [11]:
#logistic regression
from sklearn.linear_model import LogisticRegression
lr_model = LogisticRegression()

lr_model.fit(
    X_train_smote,
    y_train_smote
)

lr_pred = lr_model.predict(X_test)

print("\nLOGISTIC REGRESSION")

print("Accuracy:",
      accuracy_score(y_test, lr_pred))

print("Precision:",
      precision_score(y_test, lr_pred))

print("Recall:",
      recall_score(y_test, lr_pred))

print("ROC-AUC:",
      roc_auc_score(y_test, lr_pred))

print(confusion_matrix(y_test, lr_pred))

print(classification_report(y_test, lr_pred))


LOGISTIC REGRESSION
Accuracy: 0.9752229232016354
Precision: 0.05420054200542006
Recall: 0.8888888888888888
ROC-AUC: 0.9321244783331764
[[55260  1396]
 [   10    80]]
              precision    recall  f1-score   support

           0       1.00      0.98      0.99     56656
           1       0.05      0.89      0.10        90

    accuracy                           0.98     56746
   macro avg       0.53      0.93      0.54     56746
weighted avg       1.00      0.98      0.99     56746



In [14]:
# random forest
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    precision_score,
    recall_score,
    roc_auc_score,
    confusion_matrix,
    classification_report
)

rf_model = RandomForestClassifier(
    n_estimators=20,
    random_state=42,
    max_depth=10
)

rf_model.fit(
    X_train_smote,
    y_train_smote
)

rf_pred = rf_model.predict(X_test)

print("\nRANDOM FOREST")

print("Accuracy:",
      accuracy_score(y_test, rf_pred))

print("Precision:",
      precision_score(y_test, rf_pred))

print("Recall:",
      recall_score(y_test, rf_pred))

print("ROC-AUC:",
      roc_auc_score(y_test, rf_pred))

print(confusion_matrix(y_test, rf_pred))

print(classification_report(y_test, rf_pred))


RANDOM FOREST
Accuracy: 0.9977267120149438
Precision: 0.3945945945945946
Recall: 0.8111111111111111
ROC-AUC: 0.9045671342056544
[[56544   112]
 [   17    73]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00     56656
           1       0.39      0.81      0.53        90

    accuracy                           1.00     56746
   macro avg       0.70      0.90      0.76     56746
weighted avg       1.00      1.00      1.00     56746



In [15]:
!pip install xgboost

In [16]:
from xgboost import XGBClassifier

In [17]:
# XGBOOST MODEL

xgb_model = XGBClassifier(
    n_estimators=20,
    learning_rate=0.1,
    max_depth=5,
    random_state=42,
    eval_metric='logloss'
)

# Train model

xgb_model.fit(
    X_train_smote,
    y_train_smote
)

# Predictions

xgb_pred = xgb_model.predict(X_test)

print("\nXGBOOST RESULTS")

print("Accuracy:",
      accuracy_score(y_test, xgb_pred))

print("Precision:",
      precision_score(y_test, xgb_pred))

print("Recall:",
      recall_score(y_test, xgb_pred))

print("ROC-AUC:",
      roc_auc_score(y_test, xgb_pred))

print("\nConfusion Matrix:")

print(confusion_matrix(y_test, xgb_pred))

print("\nClassification Report:")

print(classification_report(y_test, xgb_pred))


XGBOOST RESULTS
Accuracy: 0.986783209389208
Precision: 0.09558823529411764
Recall: 0.8666666666666667
ROC-AUC: 0.9268203426527347

Confusion Matrix:
[[55918   738]
 [   12    78]]

Classification Report:
              precision    recall  f1-score   support

           0       1.00      0.99      0.99     56656
           1       0.10      0.87      0.17        90

    accuracy                           0.99     56746
   macro avg       0.55      0.93      0.58     56746
weighted avg       1.00      0.99      0.99     56746



In [18]:
from sklearn.ensemble import IsolationForest
import numpy as np
# Isolation Forest Model

iso_model = IsolationForest(
    contamination=0.001,
    random_state=42
)

# Train model

iso_model.fit(X_train)

# Predictions

iso_pred = iso_model.predict(X_test)

# Convert predictions
# -1 → Fraud
#  1 → Normal

iso_pred = np.where(
    iso_pred == -1,
    1,
    0
)

print("\nISOLATION FOREST COMPLETED")


ISOLATION FOREST COMPLETED


In [19]:
results = pd.DataFrame({

    'Model': [
        'Logistic Regression',
        'Random Forest',
        'XGBoost'
    ],

    'Accuracy': [
        accuracy_score(y_test, lr_pred),
        accuracy_score(y_test, rf_pred),
        accuracy_score(y_test, xgb_pred)
    ],

    'Precision': [
        precision_score(y_test, lr_pred),
        precision_score(y_test, rf_pred),
        precision_score(y_test, xgb_pred)
    ],

    'Recall': [
        recall_score(y_test, lr_pred),
        recall_score(y_test, rf_pred),
        recall_score(y_test, xgb_pred)
    ],

    'ROC-AUC': [
        roc_auc_score(y_test, lr_pred),
        roc_auc_score(y_test, rf_pred),
        roc_auc_score(y_test, xgb_pred)
    ]

})

print(results)

                 Model  Accuracy  Precision    Recall   ROC-AUC
0  Logistic Regression  0.975223   0.054201  0.888889  0.932124
1        Random Forest  0.997727   0.394595  0.811111  0.904567
2              XGBoost  0.986783   0.095588  0.866667  0.926820
